// Generated by scripts/generate-contributors/index.mjs — do NOT edit by hand.
// Refreshed automatically on push to main when data/restaurants/** changes;
// see .github/workflows/update-contributors.yml.
package com.novawerk.berlinfoodmap.ui.pages.settings

internal data class Contributor(
    val name: String,
    val github: String? = null,
)

internal val DATA_CONTRIBUTORS: List<Contributor> = listOf(
    Contributor(name = "Haodong Ju", github = "juhaodong"),
)
