#!/usr/bin/env node
// Regenerates the Kotlin contributors file from the git history of
// data/restaurants/. Triggered by .github/workflows/update-contributors.yml on
// every push to main that touches data/restaurants/**, and runnable locally
// with `node scripts/generate-contributors/index.mjs`.

import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = execSync('git rev-parse --show-toplevel').toString().trim();
const ALIASES_PATH = resolve(SCRIPT_DIR, 'aliases.json');
const OUTPUT_PATH = resolve(
  REPO_ROOT,
  'composeApp/src/commonMain/kotlin/com/novawerk/berlinfoodmap/ui/pages/settings/Contributors.kt',
);

// Author entries we never want to credit as data contributors.
const AUTHOR_BLOCKLIST = [
  /\[bot\]$/i,
  /^github-actions/i,
  /^claude/i, // Claude Code commits as "Claude Opus ..."
];
const EMAIL_BLOCKLIST = [
  /@anthropic\.com$/i,
  /@users\.noreply\.github\.com$/i, // only block bots; real handles still pass through extractGithub
];

// `12345+username@users.noreply.github.com` and `username@users.noreply.github.com`
function extractGithubFromEmail(email) {
  const noreply = /^(?:[0-9]+\+)?([a-zA-Z0-9](?:[a-zA-Z0-9-]{0,38}))@users\.noreply\.github\.com$/;
  const match = email.match(noreply);
  return match ? match[1] : null;
}

function isBot(name, email) {
  if (AUTHOR_BLOCKLIST.some((re) => re.test(name))) return true;
  // Block hardcoded bot emails but allow real users with noreply emails.
  for (const re of EMAIL_BLOCKLIST) {
    if (re.test(email)) {
      // Real user noreply emails pass through, only bot patterns get blocked.
      if (re.source.includes('noreply.github.com')) return false;
      return true;
    }
  }
  return false;
}

function loadAliases() {
  try {
    return JSON.parse(readFileSync(ALIASES_PATH, 'utf8'));
  } catch {
    return {};
  }
}

function escapeKotlinString(str) {
  return str.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\$/g, '\\$');
}

function collectContributors() {
  const log = execSync(
    'git log --format="%aN%x09%aE" -- data/restaurants/',
    { cwd: REPO_ROOT, maxBuffer: 10 * 1024 * 1024 },
  ).toString();

  const aliases = loadAliases();
  const seen = new Map(); // key: name|github → entry

  for (const line of log.split('\n')) {
    if (!line.trim()) continue;
    const [name, email] = line.split('\t');
    if (!name || !email) continue;
    if (isBot(name, email)) continue;

    const github = extractGithubFromEmail(email) || aliases[email.toLowerCase()] || null;
    const key = `${name}|${github ?? ''}`;
    if (!seen.has(key)) {
      seen.set(key, { name, github });
    }
  }

  return [...seen.values()].sort((a, b) =>
    a.name.localeCompare(b.name, 'en', { sensitivity: 'base' }),
  );
}

function renderKotlin(contributors) {
  const lines = [
    '// Generated by scripts/generate-contributors/index.mjs — do NOT edit by hand.',
    '// Refreshed automatically on push to main when data/restaurants/** changes;',
    '// see .github/workflows/update-contributors.yml.',
    'package com.novawerk.berlinfoodmap.ui.pages.settings',
    '',
    'internal data class Contributor(',
    '    val name: String,',
    '    val github: String? = null,',
    ')',
    '',
    'internal val DATA_CONTRIBUTORS: List<Contributor> = listOf(',
  ];

  for (const { name, github } of contributors) {
    const safeName = escapeKotlinString(name);
    if (github) {
      const safeHandle = escapeKotlinString(github);
      lines.push(`    Contributor(name = "${safeName}", github = "${safeHandle}"),`);
    } else {
      lines.push(`    Contributor(name = "${safeName}"),`);
    }
  }

  lines.push(')');
  lines.push('');
  return lines.join('\n');
}

function main() {
  const contributors = collectContributors();
  const source = renderKotlin(contributors);
  writeFileSync(OUTPUT_PATH, source);
  console.log(`Wrote ${OUTPUT_PATH} with ${contributors.length} contributor(s).`);
}

main();
